### ISSUE TITLE
watchOS Support

### ISSUE THREAD

**Issue by danialzahid94** [neilco/EventSource#13]
Any plan to support the watchOS as well in the near future?

**Comment by neilco** [comment]
Maybe. It might be fun. It would help if you could tell me what's stopping it from working with watchOS.

**Comment by danialzahid94** [comment]
Currently the SDK is using `NSURLConnection`, which has been deprecated by Apple. The major change would be to port the `NSURLConnection` code to `NSURLSession` instead. (And just add the watchOS static library target)

**Comment by neilco** [comment]
`NSURLConnection` was replaced with `NSURLSession` in [1.0.3](https://github.com/neilco/EventSource/releases/tag/1.0.3) and watchOS support added in [1.0.4](https://github.com/neilco/EventSource/releases/tag/1.0.4). 

You can also use Carthage to build dynamic frameworks for iOS, macOS, and watchOS.
